services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Two listeners: one for internal Docker services, one for host access
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - kafka-net
      
  kafka-payslip-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: ["python", "kafka_payslip_consumer.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_PAYSLIP_TOPIC: payslip_extracted
      API_BASE_URL: http://host.docker.internal:8118/api
      API_KEY: ${API_KEY}
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-net
  kafka-feature-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: ["python", "kafka_feature_consumer.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_FEATURE_TOPIC: kyc.completed
      API_BASE_URL: http://host.docker.internal:8118/api
      API_KEY: ${API_KEY}
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-net
  findocs-generate-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    command: ["python", "findocs_generate_consumer.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_FINDOC_GENERATE_TOPIC: findoc-generate
      API_BASE_URL: http://host.docker.internal:8118/api
      API_KEY: ${API_KEY}
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge